# Generated by Django 3.0.3 on 2020-09-29 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('Fruit_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FrName', models.CharField(default='Banana', max_length=200)),
                ('Season_Fruit', models.PositiveSmallIntegerField(choices=[(1, 'ฤดูร้อน'), (2, 'ฤดูฝน'), (3, 'ฤดูหนาว')], default=1)),
                ('Price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Farm')),
                ('Fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Fruit')),
            ],
        ),
    ]
