# Generated by Django 3.0.3 on 2020-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='img',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
