# Generated by Django 2.2.7 on 2020-09-16 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fruit_ID', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fruit_Name', models.CharField(max_length=200)),
                ('Season_of_Fruit', models.CharField(max_length=200)),
                ('FruitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Fruit')),
            ],
        ),
    ]
