# Generated by Django 3.0.3 on 2020-09-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='Fruit_ID',
            new_name='id',
        ),
    ]
