# Generated by Django 3.0.3 on 2020-09-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_fruit_fruit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farm_ID', models.IntegerField()),
                ('Farm_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fruit_type',
            name='Fruit_Price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fruit',
            name='Fruit_ID',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
