# Generated by Django 3.0.3 on 2020-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20200929_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='Season_Fruit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ฤดูร้อน'), (2, 'ฤดูฝน'), (3, 'ฤดูหนาว'), (4, 'ทุกฤดู')], default=1),
        ),
    ]
